version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
       - redis-data:/data:cached
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
  web: &app
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        RAILS_ENV: development
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle:cached
      - sockets:/app/tmp/sockets
      - /app/tmp
      - /app/log
      - /app/.git
    environment:
      HOME: /app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    links:
      - db
      - chrome
      - redis
  nginx:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    volumes:
      - sockets:/app/tmp/sockets
      - tmp-data:/app/tmp
    ports:
      - "80:80"
    links:
      - web
  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle:cached
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"
    stdin_open: false
    tty: false
    links: []

volumes:
  bundle:
    driver: local
  data:
    driver: local
  redis-data:
    driver: local
  sockets:
  tmp-data:
