version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data:cached
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
       - redis-data:/data:cached
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
  web: &app
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        RAILS_ENV: development
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle:cached
      - /app/tmp
      - /app/log
      - /app/.git
      - sockets:/app/tmp/sockets
    environment:
      HOME: /app
    ports:
      - "3000:3000"
      - "3035:3035"
    stdin_open: true
    tty: true
    links:
      - db
      - chrome
      - redis
  spring:
    <<: *app
    command: bundle exec spring server
    ports: []
  nginx:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - sockets:/app/tmp/sockets
    depends_on:
      - web

volumes:
  bundle:
    driver: local
  data:
    driver: local
  redis-data:
    driver: local
  sockets:
